Repository ZK-Garage/plonk, pull requests merged in 2022-02, with the labels that each got.

#110 Benchmarks
  Cargo.toml
  benches/plonk.rs
Labels: T-bench

#84 Refactor prover to include lookups
  plonk-core/Cargo.toml
  plonk-core/src/constraint_system/arithmetic.rs
  plonk-core/src/constraint_system/boolean.rs
  plonk-core/src/constraint_system/composer.rs
  plonk-core/src/constraint_system/ecc/curve_addition/fixed_base_gate.rs
  plonk-core/src/constraint_system/ecc/curve_addition/variable_base_gate.rs
  plonk-core/src/constraint_system/logic.rs
  plonk-core/src/constraint_system/lookup.rs
  plonk-core/src/constraint_system/mod.rs
  plonk-core/src/constraint_system/range.rs
  plonk-core/src/lookup/multiset.rs
  plonk-core/src/lookup/preprocess.rs
  plonk-core/src/permutation/mod.rs
  plonk-core/src/proof_system/linearisation_poly.rs
  plonk-core/src/proof_system/permutation.rs
  plonk-core/src/proof_system/preprocess.rs
  plonk-core/src/proof_system/proof.rs
  plonk-core/src/proof_system/prover.rs
  plonk-core/src/proof_system/quotient_poly.rs
  plonk-core/src/proof_system/widget/lookup.rs
  plonk-core/src/proof_system/widget/mod.rs
Labels: D-medium, P-high, T-feature, T-refactor

#118 New blinders
  benches/plonk.rs
  examples/simple_circuit.rs
  plonk-core/src/circuit.rs
  plonk-core/src/constraint_system/composer.rs
  plonk-core/src/constraint_system/helper.rs
  plonk-core/src/permutation/mod.rs
  plonk-core/src/proof_system/preprocess.rs
  plonk-core/src/proof_system/prover.rs
  plonk-core/src/proof_system/quotient_poly.rs
  plonk-core/src/proof_system/widget/mod.rs
Labels: D-easy, T-performance
